use crate::paths;

/// 一个 XML 配置属性（`<property><name>..</name><value>..</value></property>`）。
#[derive(Debug, Clone)]
pub struct XmlProperty {
    pub name: String,
    pub value: String,
}

impl XmlProperty {
    pub fn new(name: &str, value: impl Into<String>) -> Self {
        XmlProperty { name: name.to_string(), value: value.into() }
    }
}

/// 生成 Hadoop 伪分布式配置并写入配置副本。
///
/// `ports` 为探活端口（顺序：NameNode WebUI / DataNode / YARN RM WebUI / NodeManager
/// [/ JobHistory WebUI]，第 5 个仅历史服务器开启时存在），由 `config::compute_detect_ports`
/// 计算（默认 + 占用避让），写进配置保证一致。
pub fn write_hadoop_pseudo_config(name: &str, version: &str, ports: &[u16]) -> Result<(), String> {
    let etc = paths::etc_instance_dir(name, version).map_err(|e| e.to_string())?;
    let data_root = paths::var_data_instance_dir(name, version)
        .map_err(|e| e.to_string())?;

    let nn_dir = data_root.join("name").display().to_string();
    let dn_dir = data_root.join("data").display().to_string();

    std::fs::create_dir_all(&data_root).map_err(|e| e.to_string())?;

    let nn_web = ports.first().copied().filter(|p| *p > 0).unwrap_or(9870);
    let dn = ports.get(1).copied().filter(|p| *p > 0).unwrap_or(9864);
    let rm = ports.get(2).copied().filter(|p| *p > 0).unwrap_or(8088);
    let nm = ports.get(3).copied().filter(|p| *p > 0).unwrap_or(8042);

    let core_props = vec![XmlProperty::new("fs.defaultFS", "hdfs://localhost:8020")];
    write_properties(&etc.join("core-site.xml"), &core_props)?;

    let hdfs_props = vec![
        XmlProperty::new("dfs.namenode.name.dir", nn_dir),
        XmlProperty::new("dfs.datanode.data.dir", dn_dir),
        XmlProperty::new("dfs.replication", "1"),
        XmlProperty::new("dfs.namenode.http-address", format!("localhost:{nn_web}")),
        XmlProperty::new("dfs.datanode.http.address", format!("0.0.0.0:{dn}")),
        // 单机伪分布式：SecondaryNameNode 绑定 localhost，避免 ssh 分发
        XmlProperty::new("dfs.namenode.secondary.http-address", "localhost:50090"),
    ];
    write_properties(&etc.join("hdfs-site.xml"), &hdfs_props)?;

    let yarn_props = vec![
        XmlProperty::new("yarn.resourcemanager.hostname", "localhost"),
        XmlProperty::new("yarn.resourcemanager.webapp.address", format!("localhost:{rm}")),
        XmlProperty::new("yarn.nodemanager.webapp.address", format!("0.0.0.0:{nm}")),
    ];
    write_properties(&etc.join("yarn-site.xml"), &yarn_props)?;

    // 历史服务器开启时（探活端口第 5 个），写 mapred-site.xml
    if ports.len() > 4 {
        write_mapred_config(name, version, ports[4])?;
    }

    Ok(())
}

/// 写 MapReduce JobHistory 配置到 `mapred-site.xml`（文件不存在则创建空模板）。
pub fn write_mapred_config(name: &str, version: &str, history_web: u16) -> Result<(), String> {
    let etc = paths::etc_instance_dir(name, version).map_err(|e| e.to_string())?;
    std::fs::create_dir_all(&etc).map_err(|e| e.to_string())?;
    let path = etc.join("mapred-site.xml");
    if !path.exists() {
        std::fs::write(&path, "<?xml version=\"1.0\"?>\n<configuration>\n</configuration>\n")
            .map_err(|e| format!("创建 mapred-site.xml 失败: {e}"))?;
    }
    let props = vec![XmlProperty::new(
        "mapreduce.jobhistory.webapp.address",
        format!("localhost:{history_web}"),
    )];
    write_properties(&path, &props)
}

/// 生成 Kafka 简化 KRaft 配置（`server.properties`）到配置副本（默认端口 9092）。
pub fn write_kafka_config(name: &str, version: &str) -> Result<(), String> {
    let etc = paths::etc_instance_dir(name, version).map_err(|e| e.to_string())?;
    let data_root = paths::var_data_instance_dir(name, version)
        .map_err(|e| e.to_string())?;
    std::fs::create_dir_all(&data_root).map_err(|e| e.to_string())?;

    let content = format!(
        "# Generated by SoloStack\n\
         process.roles=broker,controller\n\
         node.id=1\n\
         controller.quorum.voters=1@localhost:9093\n\
         listeners=PLAINTEXT://:9092,CONTROLLER://:9093\n\
         inter.broker.listener.name=PLAINTEXT\n\
         controller.listener.names=CONTROLLER\n\
         log.dirs={}\n\
         num.partitions=1\n\
         offsets.topic.replication.factor=1\n\
         transaction.state.log.replication.factor=1\n\
         transaction.state.log.min.isr=1\n",
        data_root.join("kafka").display(),
    );

    std::fs::create_dir_all(&etc).map_err(|e| e.to_string())?;
    std::fs::write(etc.join("server.properties"), content).map_err(|e| format!("写入 Kafka 配置失败: {e}"))?;
    Ok(())
}

/// 把属性注入到 XML 文件的 `<configuration>` 节点内并写回。
fn write_properties(path: &std::path::Path, props: &[XmlProperty]) -> Result<(), String> {
    let content = std::fs::read_to_string(path).map_err(|e| format!("读取 {} 失败: {e}", path.display()))?;
    let rendered = render_xml(&content, props)?;
    std::fs::write(path, rendered).map_err(|e| format!("写入 {} 失败: {e}", path.display()))
}

/// 渲染：把 `<configuration>` 节点内的属性整体替换为给定列表（幂等）。
fn render_xml(original: &str, props: &[XmlProperty]) -> Result<String, String> {
    let open = "<configuration>";
    let close = "</configuration>";
    let start = original
        .find(open)
        .ok_or("配置文件中未找到 <configuration> 节点")?;
    let end = original
        .rfind(close)
        .ok_or("配置文件中未找到 </configuration> 节点")?;

    let head = &original[..start + open.len()];
    let tail = &original[end..];

    let mut prop_xml = String::new();
    for p in props {
        prop_xml.push_str(&format!(
            "  <property>\n    <name>{}</name>\n    <value>{}</value>\n  </property>\n",
            p.name, p.value
        ));
    }
    Ok(format!("{head}\n{prop_xml}{tail}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_xml_injects_properties() {
        let original = "<?xml version=\"1.0\"?>\n<configuration>\n</configuration>";
        let props = vec![
            XmlProperty::new("fs.defaultFS", "hdfs://localhost:9870"),
            XmlProperty::new("dfs.replication", "1"),
        ];
        let out = render_xml(original, &props).unwrap();
        assert!(out.contains("<name>fs.defaultFS</name>"));
        assert!(out.contains("<value>hdfs://localhost:9870</value>"));
        assert!(out.contains("<name>dfs.replication</name>"));
        assert!(out.contains("</configuration>"));
        let props_end = out.rfind("dfs.replication</name>").unwrap();
        let close_idx = out.rfind("</configuration>").unwrap();
        assert!(props_end < close_idx);
    }

    #[test]
    fn render_xml_missing_close_errors() {
        let err = render_xml("<configuration>", &[]);
        assert!(err.is_err());
    }
}
